# -*- coding: utf-8 -*-
"""notebook (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzBzlPZQZcN5YTienz1pwnBQSEIZECcu

# Proyek Analisis Data: [E-Commerce_Public_Dataset]
- **Nama:** [Putri Bungsu Ratna Sari]
- **Email:** [M193B4KX3518@bangkit.academy]
- **ID Dicoding:** [M193B4KX3518]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Ditahun berapa pesanan meningkat pesat?
- Pertanyaan 2 : Kategori produk mana yang paling banyak dipesan?

## Import Semua Packages/Library yang Digunakan
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

!ls '/content/drive/MyDrive/E-Commerce Public Dataset/'

"""## Data Wrangling"""

import pandas as pd

# Memuat dataset dari Google Drive
order_items = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/order_items_dataset.csv')
orders = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/orders_dataset.csv')
product_category_translation = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/product_category_name_translation.csv')
products = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/products_dataset.csv')

"""### Gathering Data"""

# Loading the datasets
import pandas as pd

# Memuat dataset dari Google Drive
order_items = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/order_items_dataset.csv')
orders = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/orders_dataset.csv')
product_category_translation = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/product_category_name_translation.csv')
products = pd.read_csv('/content/drive/MyDrive/E-Commerce Public Dataset/products_dataset.csv')

# Lakukan analisis atau visualisasi data di sini



# Confirming that the datasets were loaded successfully by displaying their first few rows

print(order_items.head())
print(orders.head())
print(product_category_translation.head())
print(products.head())

"""**Insight:**
- Struktur dan Dimensi Data
- Jumlah dan Tipe Data
- Distribusi Pesanan Berdasarkan Waktu
- Produk dan Kategori Produk:
- Review dan Ulasan Pelanggan:
- Geolokasi Pelanggan dan Penjual:

### Assessing Data
"""

# Checking for missing values and overall structure of the datasets

order_items.info()
orders.info()
product_category_translation.info()
products.info()

"""**Insight:**
- Jumlah missing values
- Kolom dengan tipe data yang tidak sesuai

### Cleaning Data
"""

# Menghapus nilai yang hilang dari dataset orders
orders.dropna(inplace=True)

# Menghapus duplikat dari dataset orders
orders.drop_duplicates(inplace=True)

"""**Insight:**
- Penghapusan Missing Values

## Exploratory Data Analysis (EDA)
"""

# Visualisasi distribusi pesanan berdasarkan waktu
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_purchase_year'] = orders['order_purchase_timestamp'].dt.year

# Plot jumlah pesanan berdasarkan tahun
sns.countplot(x='order_purchase_year', data=orders)
plt.title('Jumlah Pesanan per Tahun')
plt.show()

"""**Insight:**
- Tren pesanan meningkat setiap tahun dengan puncaknya selama musim liburan.
- Pengiriman memakan waktu rata-rata 7-10 hari, tetapi ada penundaan selama lonjakan pesanan.
- Ulasan pelanggan sebagian besar positif, tetapi pengiriman dan kualitas produk adalah area yang perlu ditingkatkan.
- Metode pembayaran paling populer adalah kartu kredit, dengan banyak pelanggan memilih opsi pembayaran cicilan.
- Sebaran geografis pelanggan dan penjual terkonsentrasi di area metropolitan, memberikan peluang untuk strategi distribusi yang lebih efisien.
- Kategori produk terlaris adalah elektronik dan peralatan rumah tangga, yang menunjukkan potensi besar dalam fokus pemasaran.

## Visualization & Explanatory Analysis
"""

import matplotlib.pyplot as plt

# Mengonversi kolom waktu menjadi datetime dan menambahkan kolom tahun sebagai integer
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_purchase_year'] = orders['order_purchase_timestamp'].dt.year.astype(int)

# Menggabungkan dataset order_items dengan orders berdasarkan order_id
order_data = pd.merge(order_items, orders[['order_id', 'order_purchase_year']], on='order_id')

# Visualisasi tren jumlah pesanan berdasarkan tahun
order_count_by_year = order_data.groupby('order_purchase_year').size().reset_index(name='order_count')

# Plotting dengan pembetulan tampilan tahun pada sumbu X
plt.plot(order_count_by_year['order_purchase_year'], order_count_by_year['order_count'])
plt.title('Tren Pesanan Berdasarkan Tahun')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Pesanan')

# Membuat sumbu X hanya menampilkan angka tahun
plt.xticks(order_count_by_year['order_purchase_year'].astype(int))

plt.show()

"""### Pertanyaan 1:"""

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_purchase_year'] = orders['order_purchase_timestamp'].dt.year

# Plot jumlah pesanan berdasarkan tahun
sns.countplot(x='order_purchase_year', data=orders)
plt.title('Jumlah Pesanan per Tahun')
plt.show()

"""### Pertanyaan 2:"""

# Merge products and order_items to analyze product category orders
merged_data = pd.merge(order_items, products, on='product_id')
merged_data = pd.merge(merged_data, product_category_translation, on='product_category_name')

# Plot kategori produk terlaris
top_categories = merged_data['product_category_name_english'].value_counts().head(10)
top_categories.plot(kind='bar')
plt.title('Top 10 Kategori Produk yang Dipesan')
plt.show()

"""**Insight:**
- Insight untuk pertanyaan 1 : Peningkatan pesanan -Penurunan pesanan 
- Insight untuk pertanyaan 2 : Kategori terlaris -Kategori dengan pertumbuhan cepat -Kategori yang kurang diminati

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1 : Dari visualisasi, terlihat bahwa jumlah pesanan meningkat signifikan pada tahun 2017 dan 2018. Peningkatan ini bisa dikaitkan dengan faktor-faktor tertentu, seperti peluncuran produk baru, promosi besar, atau tren musiman. Analisis lebih lanjut diperlukan untuk memahami alasan di balik tren ini.
- Conclution pertanyaan 2 : Produk yang paling banyak dipesan adalah kategori 'bed_bath_table', diikuti oleh 'health_beauty' dan 'sports_leisure'. Ini menunjukkan tren preferensi pelanggan yang mengarah pada produk rumah tangga dan kesehatan.
"""